spring:
  application:
    name: eureka-server
---
spring:
  profiles: peer1
server:
  port: 9700
eureka:
  client:
    serviceUrl:
      defaultZone: http://peer2:8761/eureka/
---
spring:
  profiles: peer2
server:
  port: 8761
eureka:
  client:
    serviceUrl:
      defaultZone: http://peer1:9700/eureka/


    